// <auto-generated />
using System;
using ChatApp.Model.Contexts.ChatApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChatApp.Model.Migrations
{
    [DbContext(typeof(ChatAppDbContext))]
    [Migration("20200425054015_AddedSeedData")]
    partial class AddedSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChatApp.Model.Entities.ChatRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChatRoomCode");

                    b.Property<string>("ChatRoomName");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTimeOffset?>("CreatedDate");

                    b.Property<bool>("Deleted");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTimeOffset?>("UpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("ChatRooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChatRoomCode = "f1fd1f5b-a1df-4257-82c9-c305f46546a2",
                            ChatRoomName = "Room Chat 1",
                            Deleted = false
                        },
                        new
                        {
                            Id = 2,
                            ChatRoomCode = "0b729dc1-2b84-49b7-ad90-4f15cbaf09e1",
                            ChatRoomName = "Room Chat 2",
                            Deleted = false
                        },
                        new
                        {
                            Id = 3,
                            ChatRoomCode = "c13705b9-0518-479f-8caf-66bb576a7cdc",
                            ChatRoomName = "Room Chat 3",
                            Deleted = false
                        });
                });

            modelBuilder.Entity("ChatApp.Model.Entities.ChatRoomMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChatRoomId");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTimeOffset?>("CreatedDate");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Message");

                    b.Property<string>("MessageFromUser");

                    b.Property<DateTime>("MessageTime");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTimeOffset?>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("ChatRoomId");

                    b.ToTable("ChatRoomMessages");
                });

            modelBuilder.Entity("ChatApp.Model.Entities.KeyValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTimeOffset?>("CreatedDate");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Name");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTimeOffset?>("UpdatedDate");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("KeyValues");
                });

            modelBuilder.Entity("ChatApp.Model.Entities.ChatRoomMessage", b =>
                {
                    b.HasOne("ChatApp.Model.Entities.ChatRoom", "ChatRoom")
                        .WithMany("Messages")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
